development:
  adapter: postgresql
  database: property_management
  host: localhost 
  pool: 5
  timeout: 5000

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  database: property_management
  host: localhost 
  pool: 5
  timeout: 5000

